# Generated by Django 4.1.8 on 2023-04-20 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0064_clear_search_cache'),
        ('netbox_tunnels2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunnel',
            name='b_pub_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tunnel_b_pub_address', to='ipam.ipaddress'),
        ),
    ]
