# Generated by Django 4.1.10 on 2023-08-22 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_tunnels2', '0003_tunnel_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunnel',
            name='side_a_assigned_object_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'dcim'), ('model', 'interface')), models.Q(('app_label', 'virtualization'), ('model', 'interfaces'))), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='side_a_assigned_object_type', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='tunnel',
            name='side_b_assigned_object_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'dcim'), ('model', 'interface')), models.Q(('app_label', 'virtualization'), ('model', 'interfaces'))), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='side_b_assigned_object_type', to='contenttypes.contenttype'),
        ),
    ]
